### ISSUE TITLE
Calibration problem

### ISSUE THREAD

**Issue by jacekow** [wecassidy/AnalogShield#1]
Hi,
I 've got this bug during the AnalogShield (DAC calibration:
>>> a.dac_calibrate(0, multimeter)
-4.987
-3.987
-2.987
-1.986
-0.9869
0.0133
1.014
2.0142
3.014
4.013
5.014
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    a.dac_calibrate(0, multimeter)
  File "H:\ARDUINO DUE LABVIEW\analogshield-Varia\circumflex\AnalogShield.py", line 233, in dac_calibrate
    self.dac_correct[channel] = np.poly1d(np.polyfit(dac_output, input_v, 1))
  File "<__array_function__ internals>", line 6, in polyfit
  File "H:\python353\lib\site-packages\numpy\lib\polynomial.py", line 592, in polyfit
    x = NX.asarray(x) + 0.0
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
>>> 

What could be the problem?

**Comment by jacekow** [comment]
I also checked the issue for Python 3.7.5 it is exactly the same:
>>> a.dac_calibrate(0, multimeter)
-4.987
-3.987
-2.987
-1.9875
-0.987
0.0133
1.014
2.0142
3.013
4.013
5.014
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    a.dac_calibrate(0, multimeter)
  File "H:\ARDUINO\circumflex\AnalogShield.py", line 233, in dac_calibrate
    self.dac_correct[channel] = np.poly1d(np.polyfit(dac_output, input_v, 1))
  File "<__array_function__ internals>", line 6, in polyfit
  File "C:\Users\Jacek\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\polynomial.py", line 592, in polyfit
    x = NX.asarray(x) + 0.0
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

**Comment by jacekow** [comment]
I've found the problem with passing the voltage value in my code; sorry to bother you
regards

**Comment by wecassidy** [comment]
Glad you fixed the problem. It's really nice to know other people are using my code!

**Comment by jacekow** [comment]
Thanks for your mail. I find your program very useful and complete. I am
very fond of AnalogShield boards.
(As I am new to Python and you may hear from me in case of serious
troubles).
All the best

sob., 21 gru 2019 o 16:54 Wesley Cassidy <notifications@github.com>
napisał(a):
